export default {
  FETCHING_CLASS_DATA: "FETCHING_CLASS_DATA",
  FETCHING_STUDENT_DATA: "FETCHING_STUDENT_DATA",
  FETCHING_SUBJECT_DATA: "FETCHING_SUBJECT_DATA",
  FETCHING_LIST_DATA: "FETCHING_LIST_DATA"
}
